### ISSUE TITLE
Error in uniquesToFasta

### ISSUE THREAD

**Issue by m-ocejo** [johnchase/amplicon-pipeline#2]
Hi!
I am having trouble to write the rep_set.fna file. I have paired-end data and supposed that instead of using dada_seqs in the 
uniquesToFasta(dada_seqs, "rep_set.fna") I have to use "mergers". Am I wrong? This is the error message:
Error in getUniques(unqs, collapse = FALSE) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

I tried to use seqtab.nochim as input and seems working. Is that OK? Thanks!

**Comment by johnchase** [comment]
@m-ocejo Thanks for looking at this repository. I wrote this a while ago now as a brief tutorial for some fellow lab members and co-workers, however this repository is not maintained - which may be why you are running into errors. The tutorial here was intended to show how DADA2 could be used with QIIME, however now that QIIME2 has been released and it makes use of DADA2 that is the far better option for your data analysis. You can find a list of QIIME2 tutorials [here](https://docs.qiime2.org/2.0.6/tutorials/). If you are interested in DADA2 only you should reference the [DADA2 tutorial](http://benjjneb.github.io/dada2/tutorial.html)

**Comment by m-ocejo** [comment]
Thanks John!
Do you recommend using QIIME2 eventhough it is still in alpha version? Or better wait until the beta version is released?

**Comment by johnchase** [comment]
I use QIIME2 for everything, though I came out of the lab that develops it so I may be somewhat partial. The biggest issue that you may run into is that there is some functionality that they are still developing. They do provide great support on their [forum](https://forum.qiime2.org/) and I find the interface to be quite simple - they have both a command line and API interface.
